Handling Incorrect Data

In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    "id":[1,3,5,7,9],
    "name":["John","Jane","Jennifer","Johan","Jeff"],
    "age":[25,-32,19,42,"55"],
    "gender" : ["M","M","Z","F","F"],
    "income":[400, 700, 300, np.nan, 600]
})

data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane  -32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [2]:
data.dtypes

id          int64
name          str
age        object
gender        str
income    float64
dtype: object

In [3]:
# Negative Age
data = data.astype({"age": "int32"})

data.age = abs(data.age)

data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane   32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [4]:
# Incorrect Gender
data = data[data.gender.isin(["M", "F"])]

In [5]:
# Fill na values
mean = round(data.income.mean(), 1)
data.income = data.income.fillna(mean)

In [6]:
data

   id   name  age gender  income
0   1   John   25      M   400.0
1   3   Jane   32      M   700.0
3   7  Johan   42      F   566.7
4   9   Jeff   55      F   600.0